from scipy.stats import kruskal
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt

# import os
# # --- 1. DATOS DE EJEMPLO ---
# # Usamos el mismo DataFrame para la consistencia
# data = {
#     'Valor': [20, 22, 25, 23, 27, 
#               15, 18, 17, 19, 16, 
#               30, 32, 35, 31, 34],
#     'Grupo': ['Cepa A', 'Cepa A', 'Cepa A', 'Cepa A', 'Cepa A',
#               'Cepa B', 'Cepa B', 'Cepa B', 'Cepa B', 'Cepa B',
#               'Cepa C', 'Cepa C', 'Cepa C', 'Cepa C', 'Cepa C']
# }
# df = pd.DataFrame(data)

# # --- 2. PREPARACIÓN PARA KRUSKAL-WALLIS Y PLOTEO ---

# # Crea la lista de arrays, uno por cada grupo (necesario para scipy.stats)
# grupos_separados = [df['Valor'][df['Grupo'] == g].values for g in df['Grupo'].unique()]
# nombres_grupos = df['Grupo'].unique()

# # Ejecutar la prueba
# H_statistic, p_value = stats.kruskal(*grupos_separados)

# print("--- Resultado de la Prueba de Kruskal-Wallis ---")
# print(f"Estadístico H: {H_statistic:.4f}")
# print(f"Valor p: {p_value:.4f}")
# print("-" * 40)

# # --- 3. GRÁFICO BOXPLOT CON MATPLOTLIB ---

# plt.figure(figsize=(8, 6))

# # La función boxplot de Matplotlib toma una lista de arrays como entrada
# plt.boxplot(grupos_separados, 
#             labels=nombres_grupos, # Nombres en el eje X
#             patch_artist=True,    # Permite colorear las cajas
#             medianprops={'color': 'red'}, # Estilo para la mediana
#             boxprops={'facecolor': 'lightblue'} # Color de la caja
#            )

# # Opcional: Añadir un título y etiquetas
# plt.title('Comparación de Valores por Grupo (Kruskal-Wallis)')
# plt.xlabel('Grupos (Cepas/Tratamientos)')
# plt.ylabel('Valor de Crecimiento/Metabolito')
# plt.grid(axis='y', linestyle='--', alpha=0.7)

# # Opcional: Añadir el resultado p al gráfico para contexto
# plt.text(0.5, df['Valor'].max() * 1.05, 
#          f'Kruskal-Wallis: p={p_value:.3e}', 
#          ha='center', fontsize=10, 
#          bbox=dict(facecolor='white', alpha=0.5))

# plt.show()

###############################################
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import numpy as np # Import numpy if not already done
# --- Assuming necessary imports are at the start ---

# --- 1. DATA LOADING (Assuming the merge key should be 'Model ID') ---
df1_reacs = pd.read_csv('04_resultados/rizo/reacciones/reacciones_totales_reactions_dimont_carveme_lb_4.csv')
df2_reacs = pd.read_csv('04_resultados/rizo/reacciones/reacciones_totales_reactions_prokka_carveme_lb_4.csv')
df3_reacs = pd.read_csv('04_resultados/rizo/reacciones/reacciones_totales_eggnog_carveme.csv')

# --- 2. FUSION and SYNCHRONIZATION (Ensure column name consistency) ---

# NOTE: The join key is assumed to be 'Model ID' (with a space).
# If your CSV uses 'Model_ID', please ensure consistency across all DFs.
JOIN_KEY = 'Model_ID' # Using the common convention

# Step A: Merge Dimont (df1) and Prokka (df2)
df_temp = pd.merge(
    df1_reacs, 
    df2_reacs, 
    on=JOIN_KEY, 
    how='inner', 
    suffixes=('_dimont', '_prokka') 
)

# Step B: Merge the result with EggNOG (df3)
df_sincronizado = pd.merge(
    df_temp, 
    df3_reacs, 
    on=JOIN_KEY, 
    how='inner' 
)

# --- 3. KRUSKAL-WALLIS SETUP (The Statistical Correction) ---

# We compare the reaction count distribution of the three columns (annotation methods)

# Note: The column names generated by the merge must be correct
# We assume the unsuffixed column is the EggNOG count.
grupos_para_kruskal = [
    df_sincronizado['Total_Reactions_dimont'].values,  # Group 1: Dimont
    df_sincronizado['Total_Reactions_prokka'].values,  # Group 2: Prokka
    df_sincronizado['Total_Reactions'].values         # Group 3: EggNOG (unsuffixed column)
]

# Ejecutar la prueba
# NOTE: The * operator unpacks the list of arrays into separate arguments
H_statistic, p_value = stats.kruskal(*grupos_para_kruskal)

print("--- Resultado de la Prueba de Kruskal-Wallis ---")
print(f"Comparación: Dimont vs Prokka vs EggNOG")
print(f"Estadístico H: {H_statistic:.4f}")
print(f"Valor p: {p_value:.4f}")
print("-" * 40)

# Interpretar (Optional, but useful)
alpha = 0.05
if p_value < alpha:
    print("La diferencia es estadísticamente significativa (p < 0.05).")
    print("Las medianas de los conteos de reacciones son diferentes entre los métodos de anotación.")
else:
    print("No hay diferencia estadísticamente significativa (p > 0.05).")



# --- ASUMIMOS QUE ESTAS VARIABLES ESTÁN DEFINIDAS POR EL ANÁLISIS KRUSKAL-WALLIS ---
# grupos_para_kruskal = [array_dimont, array_prokka, array_eggnog]
# H_statistic, p_value

# Definimos los nombres de las etiquetas para el eje X
nombres_metodos = ['Dimont', 'Prokka', 'EggNOG']

# Para posicionar el texto, usamos el valor máximo de todo el conjunto de datos
# (Esto requiere que grupos_para_kruskal sea una lista de arrays NumPy)
max_valor = np.concatenate(grupos_para_kruskal).max()


# --- BLOQUE DE GRÁFICA BOXPLOT ---

plt.figure(figsize=(8, 6))

# La función boxplot de Matplotlib toma la lista de arrays con los conteos de reacción
plt.boxplot(grupos_para_kruskal, 
             labels=nombres_metodos, # Nombres en el eje X: Dimont, Prokka, EggNOG
             patch_artist=True,    
             medianprops={'color': 'red', 'linewidth': 2}, # Mediana en rojo
             boxprops={'facecolor': 'lightblue', 'edgecolor': 'darkblue'} # Color de la caja
            )

# Opcional: Añadir el resultado p al gráfico para contexto
# Se usa el max_valor para posicionar el texto un 5% por encima del valor más alto
plt.text(1.5, max_valor * 1.05, 
          f'Kruskal-Wallis H={H_statistic:.2f}\np-value: {p_value:.3e}', 
          ha='center', fontsize=10, 
          bbox=dict(facecolor='white', alpha=0.8, edgecolor='black'))

# Configuración y etiquetas
plt.title('Diferencia de Conteo de Reacciones por Método de Anotación')
plt.xlabel('Método de Anotación', fontsize=12)
plt.ylabel('Total de Reacciones', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.show()